## Location to install dependencies to
LOCALBIN ?= $(shell pwd)/bin
$(LOCALBIN):
	mkdir -p $(LOCALBIN)

# CONTAINER_TOOL defines the container tool to be used for building images.
CONTAINER_TOOL ?= docker

# OpenEverest branch to use for OpenEverest CRD installation.
OPENEVEREST_BRANCH ?= main

# Percona Server for MySQL operator version whose CRDs match the API types
# vendored in go.mod (github.com/percona/percona-server-mysql-operator).
# Keep this in sync with go.mod when bumping the operator dependency.
PS_OPERATOR_VERSION ?= 1.2.0

# PS operator replicas to deploy alongside the provider in integration envs.
# CI sets this to 0 so suites simulate operator status.
PS_OPERATOR_REPLICA_COUNT ?= 1

# Local checkout path used when bootstrapping the OpenEverest controller for
# integration tests.
OPENEVEREST_DIR ?= _openeverest

# Image URL to use for building/pushing image targets
IMG ?= ghcr.io/openeverest/provider-percona-server-mysql-dev:latest

# Image URL for OpenEverest controller used in integration tests (must be pre-built).
OPENEVEREST_CONTROLLER_IMG ?= ghcr.io/openeverest/openeverest-controller-dev:0.0.0

# Split IMG into repository and tag for Helm values
_IMG_REPO = $(firstword $(subst :, ,$(IMG)))
_IMG_TAG  = $(lastword $(subst :, ,$(IMG)))

# k3d cluster name (must match dev/k3d_config.yaml metadata.name; k3d/k3s
# requires <= 32 characters)
K3D_CLUSTER_NAME ?= provider-ps-mysql-test

# controller-gen version
CONTROLLER_TOOLS_VERSION ?= v0.18.0
CONTROLLER_GEN ?= $(LOCALBIN)/controller-gen-$(CONTROLLER_TOOLS_VERSION)

# yq version for YAML processing
YQ_VERSION ?= v4.44.6
YQ ?= $(LOCALBIN)/yq-$(YQ_VERSION)

# golangci-lint version
GOLANGCI_LINT_VERSION ?= v2.11.3
GOLANGCI_LINT ?= $(LOCALBIN)/golangci-lint-$(GOLANGCI_LINT_VERSION)

# Helm chart directory
CHART_DIR ?= charts/provider-percona-server-mysql

.PHONY: help
help: ## Display this help.
	@awk 'BEGIN {FS = ":.*##"; printf "\nUsage:\n  make \033[36m<target>\033[0m\n"} /^[a-zA-Z_0-9-]+:.*?##/ { printf "  \033[36m%-20s\033[0m %s\n", $$1, $$2 } /^##@/ { printf "\n\033[1m%s\033[0m\n", substr($$0, 5) } ' $(MAKEFILE_LIST)

##@ Development

.PHONY: run
run: generate ## Run the provider locally.
	go run cmd/provider/main.go

.PHONY: lint
lint: golangci-lint ## Run golangci-lint.
	$(GOLANGCI_LINT) run

.PHONY: test-unit
test-unit: ## Run unit tests.
	go test -race ./... -coverprofile cover.out

##@ Code Generation

.PHONY: manifests
manifests: controller-gen ## Generate RBAC manifests using controller-gen from kubebuilder markers.
	$(CONTROLLER_GEN) rbac:roleName=manager-role paths="./..." output:rbac:dir=config/rbac
	@{ \
		echo '# This file is generated by controller-gen from kubebuilder RBAC markers.'; \
		echo '# Do not edit manually. Run `make manifests` to regenerate.'; \
		echo '#'; \
		echo '# Source markers are in internal/provider/rbac.go and other .go files'; \
		echo '# with +kubebuilder:rbac annotations.'; \
		if grep -q '^---' config/rbac/role.yaml; then sed -n '/^---/,$$p' config/rbac/role.yaml; else cat config/rbac/role.yaml; fi; \
	} > config/rbac/role.yaml.tmp
	@mv config/rbac/role.yaml.tmp config/rbac/role.yaml

.PHONY: helm-sync-rbac
helm-sync-rbac: yq ## Sync generated RBAC rules into the Helm chart.
	@echo "Syncing RBAC rules from config/rbac/role.yaml to Helm chart..."
	@{ \
		echo '# This file is generated by `make helm-sync-rbac` from config/rbac/role.yaml.'; \
		echo '# Do not edit manually. Run `make generate` to update.'; \
		$(YQ) '.rules' config/rbac/role.yaml; \
	} > $(CHART_DIR)/generated/rbac-rules.yaml
	@echo "Done."

.PHONY: generate
generate: manifests helm-sync-rbac ## Run all code generation (RBAC + Helm sync + provider spec from definition/).
	go generate ./...
	@echo "All generation complete."

.PHONY: verify
verify: ## Verify that generated files are up-to-date (for CI).
	@$(MAKE) generate
	@if git diff --quiet -- config/ $(CHART_DIR)/generated/; then \
		echo "Generated files are up-to-date."; \
	else \
		echo "ERROR: Generated files are out of date. Run 'make generate' and commit the changes."; \
		git diff -- config/ $(CHART_DIR)/generated/; \
		exit 1; \
	fi

##@ Build

.PHONY: build
build: generate ## Build provider binary.
	go build -o bin/provider cmd/provider/main.go

.PHONY: docker-build
docker-build: ## Build docker image.
	$(CONTAINER_TOOL) build -t ${IMG} .

.PHONY: docker-push
docker-push: ## Push docker image.
	$(CONTAINER_TOOL) push ${IMG}

##@ Helm

.PHONY: helm-deps
helm-deps: ## Download/update Helm chart dependencies.
	helm dependency build $(CHART_DIR)

.PHONY: helm-install
helm-install: helm-deps ## Install the provider using Helm.
	helm install provider-percona-server-mysql $(CHART_DIR) --create-namespace

.PHONY: helm-upgrade
helm-upgrade: helm-deps ## Upgrade the provider using Helm.
	helm upgrade provider-percona-server-mysql $(CHART_DIR)

.PHONY: helm-uninstall
helm-uninstall: ## Uninstall the provider using Helm.
	helm uninstall provider-percona-server-mysql

.PHONY: helm-template
helm-template: helm-deps ## Render Helm chart templates locally (dry-run).
	helm template provider-percona-server-mysql $(CHART_DIR)

##@ Testing

# Integration tests use chainsaw (https://kyverno.github.io/chainsaw/).
# Install it locally with: go install github.com/kyverno/chainsaw@latest
# Each suite is a directory under test/integration/ — see test/integration/README.md.

.PHONY: test-integration
test-integration: ## Run all integration tests against the current cluster.
	. ./test/vars.sh && chainsaw test --config ./test/integration/.chainsaw.yaml ./test/integration

.PHONY: test-integration-core
test-integration-core: ## Run core integration tests.
	. ./test/vars.sh && chainsaw test --config ./test/integration/.chainsaw.yaml ./test/integration/core

.PHONY: test-integration-backup
test-integration-backup: ## Run backup integration tests.
	. ./test/vars.sh && chainsaw test --config ./test/integration/.chainsaw.yaml ./test/integration/backup

.PHONY: test-integration-backup-datasource
test-integration-backup-datasource: ## Run backup datasource integration tests.
	. ./test/vars.sh && chainsaw test --config ./test/integration/.chainsaw.yaml ./test/integration/backup/datasource

.PHONY: test-integration-monitoring-pmm
test-integration-monitoring-pmm: ## Run PMM integration tests.
	. ./test/vars.sh && chainsaw test --config ./test/integration/.chainsaw.yaml ./test/integration/monitoring

.PHONY: test-e2e-cluster
test-e2e-cluster: ## Run E2E cluster tests (requires the PS operator).
	. ./test/vars.sh && chainsaw test --config ./test/e2e-cluster/.chainsaw.yaml ./test/e2e-cluster

.PHONY: test-integration-env-up
test-integration-env-up: openeverest-checkout ## Bootstrap the local environment for integration tests.
	$(MAKE) k3d-cluster-up
	$(MAKE) install-crds
	$(MAKE) docker-build
	$(MAKE) load-image
	$(MAKE) -C $(OPENEVEREST_DIR) docker-build-controller
	$(MAKE) load-openeverest-controller-image
	$(MAKE) deploy-provider-ci PS_OPERATOR_REPLICA_COUNT=0
	$(MAKE) -C $(OPENEVEREST_DIR) deploy-test-controller

.PHONY: test-integration-env-down
test-integration-env-down: ## Tear down the local integration test environment.
	$(MAKE) k3d-cluster-down

.PHONY: openeverest-checkout
openeverest-checkout: ## Ensure a local OpenEverest checkout exists for integration env bootstrap.
	@if [ ! -d "$(OPENEVEREST_DIR)/.git" ]; then \
		git clone --depth 1 --branch $(OPENEVEREST_BRANCH) https://github.com/openeverest/openeverest "$(OPENEVEREST_DIR)"; \
	else \
		git -C "$(OPENEVEREST_DIR)" fetch --depth 1 origin $(OPENEVEREST_BRANCH); \
		git -C "$(OPENEVEREST_DIR)" checkout --force FETCH_HEAD; \
	fi

.PHONY: test-e2e-cluster
test-e2e-cluster: ## Run E2E cluster tests (requires the PS operator).
	. ./test/vars.sh && chainsaw test --config ./test/e2e-cluster/.chainsaw.yaml ./test/e2e-cluster

.PHONY: test-e2e-cluster-datasource-backup
test-e2e-cluster-datasource-backup: ## Run backup datasource e2e-cluster test (requires a running PS operator).
	. ./test/vars.sh && chainsaw test --config ./test/e2e-cluster/.chainsaw.yaml ./test/e2e-cluster/datasource/backup

.PHONY: load-image
load-image: ## Import the provider image (IMG) into the k3d cluster.
	k3d image import ${IMG} -c ${K3D_CLUSTER_NAME}

.PHONY: load-openeverest-controller-image
load-openeverest-controller-image: ## Import the OpenEverest controller image into the k3d cluster.
	k3d image import ${OPENEVEREST_CONTROLLER_IMG} -c ${K3D_CLUSTER_NAME}

.PHONY: install-crds
install-crds: ## Install OpenEverest CRDs (and your operator's CRDs) into the cluster.
	kubectl apply -f https://raw.githubusercontent.com/openeverest/openeverest/$(OPENEVEREST_BRANCH)/config/crd/bases/core.openeverest.io_providers.yaml
	kubectl apply -f https://raw.githubusercontent.com/openeverest/openeverest/$(OPENEVEREST_BRANCH)/config/crd/bases/core.openeverest.io_instances.yaml
	kubectl apply -f https://raw.githubusercontent.com/openeverest/openeverest/$(OPENEVEREST_BRANCH)/config/crd/bases/core.openeverest.io_instancepresets.yaml
	kubectl apply -f https://raw.githubusercontent.com/openeverest/openeverest/$(OPENEVEREST_BRANCH)/config/crd/bases/monitoring.openeverest.io_monitoringconfigs.yaml
	kubectl apply -f https://raw.githubusercontent.com/openeverest/openeverest/$(OPENEVEREST_BRANCH)/config/crd/bases/backup.openeverest.io_backupclasses.yaml
	kubectl apply -f https://raw.githubusercontent.com/openeverest/openeverest/$(OPENEVEREST_BRANCH)/config/crd/bases/backup.openeverest.io_backups.yaml
	kubectl apply -f https://raw.githubusercontent.com/openeverest/openeverest/$(OPENEVEREST_BRANCH)/config/crd/bases/backup.openeverest.io_restores.yaml
	kubectl apply -f https://raw.githubusercontent.com/openeverest/openeverest/$(OPENEVEREST_BRANCH)/config/crd/bases/backup.openeverest.io_backupstorages.yaml
	# Percona Server for MySQL operator CRDs, pinned to the version in go.mod.
	kubectl apply --server-side -f https://raw.githubusercontent.com/percona/percona-server-mysql-operator/v$(PS_OPERATOR_VERSION)/deploy/crd.yaml

.PHONY: deploy-provider-ci
deploy-provider-ci: ## Deploy the provider via Helm for CI (IMG must already be imported into k3d).
	helm repo add percona https://percona.github.io/percona-helm-charts/
	helm dependency build $(CHART_DIR)
	helm upgrade --install provider-percona-server-mysql $(CHART_DIR) \
		--create-namespace \
		--namespace provider-system \
		--skip-crds \
		--set image.repository=$(_IMG_REPO) \
		--set image.tag=$(_IMG_TAG) \
		--set image.pullPolicy=Never \
		--set ps-operator.replicaCount=$(PS_OPERATOR_REPLICA_COUNT) \
		--wait --timeout 2m

.PHONY: deploy-provider-e2e
deploy-provider-e2e: ## Deploy the provider with the PS operator for E2E tests.
	helm repo add percona https://percona.github.io/percona-helm-charts/
	helm dependency build $(CHART_DIR)
	helm upgrade --install provider-percona-server-mysql $(CHART_DIR) \
		--create-namespace \
		--namespace provider-system \
		--skip-crds \
		--set image.repository=$(_IMG_REPO) \
		--set image.tag=$(_IMG_TAG) \
		--set image.pullPolicy=Never \
		--set ps-operator.replicaCount=1 \
		--wait --timeout 5m
	kubectl wait --for=condition=available --timeout=120s \
		deploy/provider-percona-server-mysql-ps-operator -n provider-system

##@ Local Development Cluster

.PHONY: k3d-cluster-up
k3d-cluster-up: ## Create a local k3d cluster for development.
	$(info Creating k3d cluster for testing)
	k3d cluster create --config ./dev/k3d_config.yaml

.PHONY: k3d-cluster-down
k3d-cluster-down: ## Delete the local k3d cluster.
	$(info Destroying k3d test cluster)
	k3d cluster delete --config ./dev/k3d_config.yaml

.PHONY: k3d-cluster-reset
k3d-cluster-reset: k3d-cluster-down k3d-cluster-up ## Reset the local k3d cluster.

##@ Tilt Development

.PHONY: dev-up
dev-up: k3d-cluster-up ## Create the k3d cluster and start the Tilt dev environment.
	tilt up -f dev/Tiltfile

.PHONY: dev-down
dev-down: ## Stop the Tilt dev environment (keeps the cluster).
	tilt down -f dev/Tiltfile

.PHONY: dev-destroy
dev-destroy: k3d-cluster-down ## Stop Tilt and delete the k3d cluster.

##@ Tool Dependencies

.PHONY: controller-gen
controller-gen: $(CONTROLLER_GEN) ## Install controller-gen.
$(CONTROLLER_GEN): $(LOCALBIN)
	$(call go-install-tool,$(CONTROLLER_GEN),sigs.k8s.io/controller-tools/cmd/controller-gen,$(CONTROLLER_TOOLS_VERSION))

.PHONY: yq
yq: $(YQ) ## Install yq.
$(YQ): $(LOCALBIN)
	@echo "Installing yq $(YQ_VERSION)..."
	@GOBIN=$(LOCALBIN) go install github.com/mikefarah/yq/v4@$(YQ_VERSION) && mv $(LOCALBIN)/yq $(YQ)

.PHONY: golangci-lint
golangci-lint: $(GOLANGCI_LINT) ## Install golangci-lint.
$(GOLANGCI_LINT): $(LOCALBIN)
	$(call go-install-tool,$(GOLANGCI_LINT),github.com/golangci/golangci-lint/v2/cmd/golangci-lint,$(GOLANGCI_LINT_VERSION))

# go-install-tool will 'go install' any package with custom target and target name. Usage:
# $(call go-install-tool,<target>,<package>,<version>)
define go-install-tool
@[ -f $(1) ] || { \
set -e; \
package=$(2)@$(3); \
echo "Installing $${package}"; \
GOBIN=$(LOCALBIN) go install $${package}; \
mv -f $$(echo "$(1)" | sed "s/-$(3)$$//") $(1); \
}
endef
