{{- if .Values.rbac.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "provider-percona-server-mysql.fullname" . }}
  labels:
    {{- include "provider-percona-server-mysql.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "provider-percona-server-mysql.fullname" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "provider-percona-server-mysql.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
{{- end }}
